services:
  api:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - MONGODB_URI=mongodb://db:27017
    volumes:
      - .:/app
      - ./files:/app/files
    depends_on:
      - db
    command: npm run start:debug -- --preserveWatchOutput true

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
