services:
  auction-api:
    build:
      context: ./auction-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - JWT_SECRET=supersecurejwtsecret
      - JWT_EXPIRES_IN=1h
      - MONGODB_URI=mongodb://mongodb:27017/auction
    volumes:
      - ./auction-api:/auction-api/app
      - ./auction-api/files:/auction-api/app/files
    command: npm run start:debug -- --preserveWatchOutput true
    depends_on:
      - mongodb
      - auth-api
  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "9230:9230"
    environment:
      - JWT_SECRET=supersecurejwtsecret
      - JWT_EXPIRES_IN=1h
      - MONGODB_URI=mongodb://mongodb:27017/auth
    volumes:
      - ./auth-api:/auth-api/app
    command: npm run start:debug -- --preserveWatchOutput true
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
