apiVersion: v1
kind: Service
metadata:
  namespace: my-app
  name: auction-api
spec:
  type: NodePort
  selector:
    app: auction-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: debug
      protocol: TCP
      port: 9229
      targetPort: 9229
