apiVersion: v1
kind: Service
metadata:
  namespace: my-app
  name: auth-api
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
    - name: debug
      protocol: TCP
      port: 9230
      targetPort: 9230
