apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: kstoyanovw/auth-api:v1.0
          ports:
            - containerPort: 3001
            - containerPort: 9230
          env:
            - name: JWT_SECRET
              value: "supersecurejwtsecret"
            - name: JWT_EXPIRES_IN
              value: "1h"
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/auth
